---
title: "Delineamento Experimental"
author: "Prof. Dr. Juliano Bortolini"
date: ""
output: html_document
---

*Doutorado em Medicina Veterinária - UFMT*

*Período letivo: 2024/2*


### Avisos:

- Última atualização do site às **`r format(Sys.time(), "%H:%M", tz="America/Cuiaba")`** do dia **`r format(Sys.time(), "%d/%m/%Y")`**.
- [Whatsapp da disciplina]()
- **[Prova 2](aulas/prova2.html): enviar por e-mail até 19-11-2024**.



### Conteúdo Programático:

**Unidade I:**

- Experimentação estatística.
- Princípios básicos da experimentação.
- Delineamento inteiramente casualizado.
- Delineamento em blocos casualizados.
- Delineamento em quadrado latino.
- Métodos de comparações múltiplas de tratamentos.

**Unidade II:**

- Experimentos fatoriais cruzados.
- Experimentos fatoriais em parcelas subdivididas.
- Experimentos fatoriais hierárquicos.

**Unidade III:**

- Modelos lineares generalizados (gama, logística, poisson e binomial negativa).
- Modelos lineares de efeitos mistos.
- Modelos de equações de estimativas generalizadas (GEE).
- Modelos aditivos generalizados para locação, escala e forma (GAMLSS).


### Notas de aula:

- Aula 1: apresentação da disciplina, variáveis contínuas e discretas, modelos lineares clássicos (distribuição normal da variável resposta) e generalizados (distribuição não normal para a variável resposta). Apresentação das pesquisas desenvolvidas pelos alunos no mestrado e em desenvolvimento no doutorado. **Tarefa 1:** listar os métodos estatísticos descritos nos artigos de referência para a pesquisa do doutorado.

- [Aula 2](aulas/aula2.html): estudo observacional, estudo experimental, objetivos da experimentação, breve história do Planejamento e Análise de Experimentos (PAE), conceitos básicos do PAE, considerações éticas, princípios básicos do PAE, erro experimental, considerações no planejamento de experimentos, comparações simples (dois tratamentos) com modelo matemático e exemplo. **Tarefa 2:** (enviado no grupo) planejar experimentos e identificar os fatores, tratamentos, delineamento, variável resposta, etc.

- Aulas 3, 4 e 5: um pouco mais sobre o planejamento de experimentos. Delineamento inteiramente casualizado (DIC): motivação com o exemplo do experimento de supressão do crescimento de bactérias, aleatorização dos tratamentos nas UEB, modelos estatísticos, teste de hipóteses, somas de quadrados, graus de liberdade e teste F. Delineamento em blocos casualizados: motivação com a restrição na aleatorização. UEB heterogêneas e controle local (blocagem). Aleatorização dos tratamentos nas UEB de cada bloco. Exemplo da produção de leite. Análise de experimento em DBC. Delineamento em quadrado latino: exemplo com mais de uma fonte de variação a ser controlada. Aleatorização no DQL. Análise de experimentos em DQL.

- Aula 6: aula prática com análise de experimentos em DIC, DBC e DQL no R. **Tarefa 3:** (enviado no grupo) análise de um experimento em R.

- [Aula 7](aulas/aula7.html): métodos de comparações múltiplas e pressupostos. **Tarefa 4:** refazer todos os exercícios da aula anterior com testes de comparações multiplas e análise dos pressupostos.

- [Tarefa 5](aulas/Tarefa5.html): exercícios gerais sobre os conteúdos das aulas anteriores.

- Aula 8: introdução aos experimentos fatoriais: conceito e definição de experimentos fatoriais, comparação com experimentos mais simples (um fator e combinações de níveis). Exemplos: avaliação de rações na produção de leite, estudo sobre medicamentos que afetam níveis de colesterol e mistura de proteína e carboidrato em rações. Estrutura dos experimentos fatoriais: definição de fatores, níveis e tratamentos, análise de efeitos simples, principais e de interação entre fatores.  Casualização dos tratamentos: delineamento inteiramente casualizado e blocos casualizados. Análise estatística no R: funções `fat2.rbd()` e `fat2.crd()` do pacote `ExpDes`.  Exemplos do livro do Kronka. Interpretação dos resultados de análise de variância (ANOVA): casos de interação significativa e não significativa, desdobramentos para estudar o comportamento de fatores dentro de outros. 

- **Tarefa 6:** experimentos fatoriais triplos: exemplos 5.3 e 5.4 do livro do Kronka.

- Aula 9: experimentos fatoriais triplos: definição, estrutura, análise de efeitos simples, principais e de interação entre fatores. Exemplos do livro do Kronka. Funções `fat3.rbd()` e `fat3.crd()` do pacote `ExpDes`.

- Aula 10: experimentos fatoriais em parcelas subdivididas: definição, estrutura, análise de efeitos simples, principais e de interação entre fatores. Exemplos do livro do Kronka. Funções `split2.crd()` e `split2.rbd()`  do pacote `ExpDes`. Experimentos hierárquicos: definição, estrutura e exemplo de diferentes doses e medicamentos (doses diferentes dentro de cada medicamento).

- [Prova 2](aulas/prova2.html): prova com questões sobre os conteúdos das unidades I e II.

- Seminário 1: modelos lineares generalizados (19/11/2024).

- Seminário 2: modelos lineares de efeitos mistos (26/11/2024).

- Seminário 3: modelos de equações de estimativas generalizadas (GEE) (03/12/2024).

- Seminário 4: modelos aditivos generalizados para locação, escala e forma (GAMLSS) (10/12/2024).


### Avaliações:

- Provas, seminário e artigo.

- $P_1$: nota da prova 1 (2,5 pontos): unidade I.
  
- $P_2$: nota da prova 2 (2,5 pontos): unidades I e II.

- $S$: nota do seminário (2,5 pontos): unidade III.

- $A$: Nota do artigo (2,5 pontos): análise de dados (dissertação, tese, pesquisas...) usando os conteúdos da disciplina.

- Nota final, $NF$: soma de todas as notas ( $P_1 + P_2 + S + A$ )

- Conceitos:  $A$ se $NF \geq9$,  $B$ se $9 > NF \geq 7,5$ ou $C$ se $7,5 > NF \geq 6$.

- Reprovação por falta se a quantidade de faltas for superior a 4 aulas de 4 horas.

**Nota bônus:** Se o artigo for aceito para publicação até a data do lançamento de notas, o aluno(a) terá conceito A na disciplina.


### Bibliografia

**Experimentação**

Montgomery, D. C. **Design and Analysis of Experiments**. New York: Wiley, 2012.

Dean, A., Voss, D., Draguljić, D. **Design and Analysis of Experiments** (2nd ed.). Springer. 2017. 

Festing, M. F. W., Altman, D. G. Guidelines for the Design and Statistical Analysis of Experiments Using Laboratory Animals. **ILAR Journal**. Volume 43, Number 4, 2002.

Freitas, A. R. de. **Estatística experimental na agropecuária**. Brasília, DF: Embrapa, 2022.

Sampaio, I. B. M. **Estatística aplicada a experimentação animal**. Belo Horizonte: FEPMV, 2015. 265p.

Banzatto, D. A., Kronka, S. N. **Experimentação agrícola**. Jaboticabal: Funep, 2006.



**Estatística geral**


Devore, Jay L.; Berk, Kenneth N.; Carlton, Matthew A. **Modern Mathematical Statistics with Applications**. 3. ed. Springer, 2021.

Petrie, A., Watson, P. **Estatística em ciência animal e veterinária**. Roca, 2009.

Baldi, B., Moore, D. S. **A prática da estatística nas ciências da vida**. LTC, 2014. 

Bussab, W. O., Morettin, P. A. **Estatística básica**. 9. ed. São Paulo: Saraivauni, 2017.




----------
<div style="text-align: center;">

[@profjulianobortolini](https://instagram.com/profjulianobortolini) \  \  \ [www.julianobortolini.com.br](http://www.julianobortolini.com.br) \  \  \ [linkedin](https://linkedin.com/in/julianobortolini) \  \  \   [github](https://github.com/julianobortolini) \  \  \   [lattes](http://lattes.cnpq.br/6210909768845403)

</div>


